### ISSUE TITLE
Error when loading application after deleting wallet

### ISSUE THREAD

**Issue by AaronFeickert** [cake-tech/cupcake#8]
To reproduce:
- Create a single wallet.
- Delete the wallet, so no wallets remain.
- Close the application.
- Start the application, entering the password.

Expected behavior:
The application loads, showing no wallets.

Actual behavior:
An error message occurs, indicating the "given wallet doesn't exist".

**Comment by MrCyjaneK** [comment]
Thanks for the report, the issue should be fixed in this PR: https://github.com/cake-tech/cupcake/pull/10
