### ISSUE TITLE
Password screen disappears

### ISSUE THREAD

**Issue by AaronFeickert** [cake-tech/cupcake#9]
To reproduce:
- Create a wallet, setting a password.
- Close the application.
- Start the application, entering the wrong password.
- Dismiss the resulting error.
- Tap any touch target on the password screen.

Expected behavior:
The password prompt responds to the touch target.

Actual behavior:
The password prompt disappears, showing a blank screen.

**Comment by MrCyjaneK** [comment]
Thanks for the report, the issue should be fixed in this PR: https://github.com/cake-tech/cupcake/pull/10
